FIND_PATH(SSVSCOLLISION_INCLUDE_DIR
  NAMES SSVSCollision/SSVSCollision.hpp
  PATH_SUFFIXES include/
  PATHS "${PROJECT_SOURCE_DIR}/../SSVSCollision/"
  "${PROJECT_SOURCE_DIR}/extlibs/SSVSCollision/"
  ${SSVSCOLLISION_ROOT}
  $ENV{SSVSCOLLISION_ROOT}
  /usr/local/
  /usr/
  /sw/       
  /opt/local/
  /opt/csw/  
  /opt/
)

message("\nFound SSVSCollision include at: ${SSVSCOLLISION_INCLUDE_DIR}.\n")

IF(SSVSCOLLISION_INCLUDE_DIR)
  SET(SSVSCOLLISION_FOUND TRUE)
ELSE(SSVSCOLLISION_INCLUDE_DIR)
  SET(SSVSCOLLISION_FOUND FALSE)
ENDIF(SSVSCOLLISION_INCLUDE_DIR)

IF(SSVSCOLLISION_FOUND)
  MESSAGE(STATUS "Found SSVSCollision in ${SSVSCOLLISION_INCLUDE_DIR}")
ELSE(SSVSCOLLISION_FOUND)
  IF(SSVSCOLLISION_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find SSVSCollision library")
  ENDIF(SSVSCOLLISION_FIND_REQUIRED)
ENDIF(SSVSCOLLISION_FOUND)

MARK_AS_ADVANCED(
  SSVSCOLLISION_INCLUDE_DIR
)
